### ISSUE TITLE
Unit icons doesn't shows

### ISSUE THREAD

**Issue by solo-s** [iainmillar23/MoarUnits#1]
No one icon doesn't shows on Mac version.
<img width="1552" alt="2017-01-15 0 00 02" src="https://cloud.githubusercontent.com/assets/5980712/21958103/4cf43178-dab6-11e6-94f3-9efc29dd8b46.png">
<img width="1552" alt="2017-01-15 0 02 22" src="https://cloud.githubusercontent.com/assets/5980712/21958099/3ada3550-dab6-11e6-93f8-59c3a08f55a5.png">

**Comment by deliverator23** [comment]
This should now be resolved in the latest version.
